fragment Post on Post {
  cuid
  dateAdded
  title
  contentMarkdown
}

query Posts($username: String!) {
  user(username: $username) {
    name
    publication {
      posts {
        ...Post
      }
    }
  }
}
